### ISSUE TITLE
Manual control on Video Quality

### ISSUE THREAD

**Issue by souravdasslg** [FrontendMasters/android-issues#36] opened 2020-05-26 16:01 UTC
I think it will be really great to have the video quality control settings on the android app.
Since I found that "adaptive video quality" is not very stable and reliable in the app, I guess its really good to have a video quality button in the player itself.

**Comment by dachev** [comment] 2020-05-26 16:07
duplicate of #19

**Closed as completed by dachev** 2020-05-26 16:07 UTC
